---
title: "Data Science Product Owner"
author: "Saif Shabou"
date: '2020-10-14'
output: html_document
featured: true
image: 
  placement: 1
  focal_point: ""
  preview_only: false
  caption: "Photo by Carol and Mike Werner / Alamy/Alamy"
---

# Intro

With the increasing number of Data Science and AI based products, we need to think more the work organization within Data teams.

Inspired by Agile Frameworks and DevOps approaches, new Data and Machine Learning development workflows are being implemented (DataOps, MLOps…). While Agile methodologies have proven their efficiency in software development organizations, some adaptations are needed in Data Science and ML areas.

We will discuss in this article one of these adaptations: The role and skill sets of **Product Owner**.

The *first section* describes quickly the main principles related to Agile methodology in traditional software development.
The *second section* presents specificities of Data and ML solutions.

In *the last setion*, I try to discuss the tasks and responsibilities of *Data Science Product Owner*.

The following graph presents the connection of different concepts and tools used for this article (with the R code embeded because it looks nicer).

```{r wbdata, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE}
library('visNetwork') 

DSPO.links <- read.csv("data/DSPO.links.csv", header=T, as.is=T, sep = ";")
DSPO.nodes <- read.csv("data/DSPO.nodes.csv", header=T, as.is=T, sep = ";")


vis.DSPO.nodes <- DSPO.nodes
vis.DSPO.links <- DSPO.links

vis.DSPO.nodes$shape  <- vis.DSPO.nodes$shape 
vis.DSPO.nodes$shadow <- TRUE # Nodes will drop shadow
vis.DSPO.nodes$title  <- vis.DSPO.nodes$concepts # Text on click
vis.DSPO.nodes$label  <- vis.DSPO.nodes$concepts # Node label
vis.DSPO.nodes$size   <- vis.DSPO.nodes$concept.size # Node size
vis.DSPO.nodes$borderWidth <- 2 # Node border width

vis.DSPO.nodes$color.background <- c("slategrey", "tomato", "gold")[vis.DSPO.nodes$concept.type]
vis.DSPO.nodes$color.border <- "black"
vis.DSPO.nodes$color.highlight.background <- "orange"
vis.DSPO.nodes$color.highlight.border <- "darkred"
vis.DSPO.nodes$font.size  <- vis.DSPO.nodes$font.size 

vis.DSPO.links$title  <- vis.DSPO.links$type # Link title
vis.DSPO.links$label  <- vis.DSPO.links$type # Link label
vis.DSPO.links$width  <- vis.DSPO.links$width # link width
vis.DSPO.links$length  <- vis.DSPO.links$length # Link length


visNetwork(vis.DSPO.nodes, vis.DSPO.links, height = "500px", width = "100%") %>% 
  visOptions(highlightNearest = list(enabled = T, degree = 2, hover = T)) %>%
  visOptions(selectedBy = "concept.category") %>%
  visLayout(randomSeed = 123) 
```

# Agile approaches in Software Development

## Agile approaches

### History

Agile approaches consist of a set of practices and values for driving and building complex IT products. They were designed in reaction to the rigidity of traditional approaches in software development (V-cycle, waterfall…). They are based on the [Agile manifesto](https://agilemanifesto.org/) written in 2001.

### Values

Agile approaches are based on an iterative, incremental and adaptive development cycle. The four fundamental values defined in the Agile manifesto are:

- Individuals and interactions over processes and tools
- Working software over comprehensive documentation
- Customer collaboration over contract negotiation
- Responding to change over following a plan


### Frameworks

There are various methodologies that offer IT product development frameworks based on the principles set out in the Agile Manifesto: **Extreme Programming (XP)**, **Scrum**, **Kanban**, **SAFe** ...We will focus on the Scrum framework for the rest of the article as it is the most adopted one.


### Roles

Scrum defines 3 roles:

- The **Product Owner** who carries the vision of the product to be achieved and considered as the representative of the customer.
- The **Scrum Master** is the responsible for the application of the Scrum method
- The **development team** that makes the product

### Work Organization

- **Sprint**: It is a relatively short period of time (2 to 4 weeks), during which the development team realizes and tests a set of features defined with the Product Owner.
- **Product Backlog**: It is an ordered and prioritized list of features constituting the IT product.
- **Items**: The Product Backlog is composed of different “items” which contain a detailed description of the components to be carried out: requirements, improvements and corrections to be made, tests, definition of “done” ...
Those items are often grouped into different groups to better manage production times: User stories, epics, features, tasks, bugs ... A list of items is selected by the team every sprint. This list constitutes the “Sprint Backlog”.
- **sprint planning**: A Scrum event during which the development team selects with the Product Owner the prioritized items from  product backlog that it considers to be able to achieve during the sprint.
- **Sprint Review **: A Scrum event that serves the development team to present the achieved features during the last sprint in order to collect feedback from the Product Owner and end users.
- **Sprint Retrospective**: A Scrum event designed for inspecting the past sprint and identifying potential improvements in terms of productivity, efficiency, working condtions...
- **Daily meeting**: A 15-minute daily standing meeting for synchronizing the daily tasks of the development team.

> You can find out a complete description of Scrum methodology [here](https://www.scrum.org/).

### Work organization tools

There are several management and planning tools for product development based on Agile methodologies. These tools offer different functionalities such as sprint reports, dashboards, definition of the roadmap, velocity monitoring ... Among these tools we can mention: [Jira](https://www.atlassian.com/fr/software/jira), [Trello](https://trello.com/fr), [Asana](https://asana.com/fr), [confluence](https://www.atlassian.com/fr/software/confluence), [Kanboard](https://kanboard.org/), [OpenProject](https://www.openproject.org/fr/), [Gitlab](https://about.gitlab.com/), [GithubProjects](https://github.com/features/project-management/), [OpenProject](https://www.openproject.org/fr/) ...

## DevOps


A combination of Development (Dev) and Operation (Ops), the Devops culture is part of agile approaches by offering work practices that encourage more collaboration and process sharing. These practices are essentially based on shorter release cycles with an increase in the frequency of deployments and continuous deliveries. 

- **Continious Integration/Continious Deployement (CI/CD)**:

  - *Continuous Integration*: Frequently integrate and merge code changes into the main code branch by setting up automated tests that run whenever new code is validated.
  - *Continuous Deployement*: Respect frequent and automated deployment of new application versions in a production environment. (Tools: Jenkins, CicleCI, Gitlab...) 
- **Version management**: Manage different versions of code and track revisions and change history to facilitate code review and retrieval. (Tools: Gitlab, Github, SourceForge, bitbucket)
- **Continious monitoring**: Set up continuous monitoring and alerting tools to have complete real-time visibility into the performance and integrity of different components of the application.


## The Product Owner

The Product Owner plays an important role in an Agile organization. We can categorize his tasks and responsibilities into 5 main families:

- **Client / team interface**: The PO is the representative of the customer and the product users in the Agile team. He/She transforms customer needs into technical features and guarantees that the product meets their expectations. He/She sets up metrics and KPIs to assess product usage and users' behavior in order to identify potential improvements.

- **Product Development management**: The PO is the master of the Backlog and the referent of product roadmap. He/She is in charge of:

  - Proposing functional specifications and ensuring the correct translation in terms of technical specifications
  - Writing User Stories and defining their acceptance criteria
  - Defining acceptance protocols and criterias 
  - Validating achievements using functional tests
  - Guarantee the of delivered features quality
  - Feeding the roadmap with Pprioritized features. 



- **Collaboration**: By nature, the PO must collaborate with different members of the development team. As product reference, he/she is also needs to coordinate with other teams and departments: sales, marketing, infrastructure, etc.

- **Communication**: The PO must share the product vision inside and outside the company. He/She can organize Product Discovery workshops with the team and clients. He/She is also responsible for the quality and completeness of the documentation.

- **Technology watch**: The PO must ensure a continuous watch on the market in order to be able to situate the product among the competition within technical and functional dimensions.

# Agile aproaches * Data Science products

In the intersection of statistics and computer science, Data Science applications are fast growing. While at the beginning, the majority of data science work stopped at the level of exploration and prototyping, increasing performance of technical tools, scientific efforts and use cases maturity have enabled the shift to idustrialized products.

These evolutions need to be accompanied by methodological tools for the management of a Data product and then rethink the application of agile approaches as well as the role of the Product Owner in Data Science workflow.

## Data Science produtcs

We can regroup Data Science products into two main catergories: Data Analytics & Machine Learning. 

- **Data Analytics**: They essentially consist of a data processing pipelines attempting to extract knowledge and insights of the studied phenomena by using collected raw data:

  - *Data Extraction*: Frequency, disponibility, schemas, formats, data models...
  - *Data Storage*: Datawarehousing, datalake, relational Databases, NoSql Databases, Cloud Storage platforms...
  - *Data Exploration*: Profiling, Descriptive statistics, visualization...
  - *Data Transformation*: Cleaning, aggregating, automatic reporting... <br/>

- **Machine Learning**: It refers to products that are based on learning models (supervised, unsupervised, self-supervised) and which generate services aiming at replacing human tasks. We can distinguish 5 families of ML solutions on the market: *recommendation and scoring systems* (e.g. movie recommendation), *prediction of actions or events* (e.g. prediction of clicks on a video), *classification* (e.g. classification of emails as spam / not spam), *generative models* (e.g. translation), and *clustering* (e.g. clients segmentation).

In addition to the data analytics pipelines, ML products integrate specific techniques:

  - *Data transformation*: division into test/train, feature engineering, data augmentation...
  - *Modeling*: testing different statistical models, hyperparameters tuning
  - *Model training*
  - *Model Evaluation and validation*
  - *Model serving*
  - *Model monitoring*
  
## DataOps & MLOps

Inspired by the Agile methodologies and DevOps culture, Data Science products are

|   | DataOps | MLOps |
| :----- |---------------- |  ---------------- |
|  CI/CD | It consists of implementing CI/CD methods for managing the developement and the orchestration of data pipelines. <br/> *(Tools: Dataflow, Luigi, Airflow...)*  | Continuous integration of testing/validating data, continious deployement of an entire ML training system and prediction services, Continious  Training by automatically retraining and serving models *(Tools: MLflow, kubeflow, Cortex...)*|
|  Version Management | The versioning of the different Data sets collected, stored, and manipulated. Some tools, such as [Data Version Control (DVC)](https://dvc.org/) and Data Catalogs propose new features for handeling this aspect. | Intgrating Model versioning features (data version, modifications, parameters, stages..)  |
|  Monitoring | Monitoring the collected and procuced data during the data pipline cycle (Data Quality, data schemas, volumetry...) and implementing alerting features for supervising these indicators. | Model monitoring by tracking prediction performance metrics (accuracy, sensitivy...), input data quality, system latency... (Tools: Amazon SageMaker, MLFlow...)|

## The Data Science Product Owner

The skills necessary to properly manage Data or ML/AI products refer to the differences between traditional IT solutions (application, website, or any software) and solutions based essentially on data. As seen above, developing a Data product requires different techniques and methods from those used to develop traditional software.

These new features will inevitably impact the product development cycle and the Product Owner, as the main referent, must be able to control them.

- **Product Development management**:

  - *Feasibility assessment*: Integrate feasibility studies into the development process.
  - *Scientific methods*: Integrate the necessary steps for a implementing scientific approach: Observation, formulation of problems, hypothesis testing, phenomenon modeling, experimentation, evaluation, demonstration, precision and accuracy
  - *Delivery*: Knowing how to define deliverables adapted to data science work which are more experimental in nature and which do not necessarily result in a new functionality
  - *Estimation*: The exploratory nature of data science and machine learning work makes the task of estimating the effort required to develop new functionality more complex. It is preferable that a Data Science PO has experience with the exploration phases to be able to propose the right metrics and methods to estimate them and integrate them into the development cycle.
  - *Data*: Since a Data Science product is essentially based on input data, the PO must know them (quality, availability, formats, source, etc.). Manipulating the data allows it to better anticipate the processing necessary to exploit it.
  - *Models*: 
  - *Validation*: The validation of Data functions often requires skills in data analysis, use of notebooks to standardize tests, mastery of model performance evaluation metrics, etc.
  
- **Collaboration**: In addition to the traditional development team, the Data Science PO must coordinate the tasks of the various profiles making up the Data team: **Data engineers**, **Data Analysts**, **Data scientists**, **Data Architects**… For this, it is important that he knows their responsibilities, skills and constraints in order to properly coordinate the development phases.

- **Technology watch**: The development of industrialized applications based on data science and machine learning models remains a fairly young profession. It is important for the data product team, and particularly the PO, to be up to date in terms of tools, techniques, methods, algorithms and technologies… This makes it possible to better anticipate the changes to be integrated in order to improve some performance.

# Conclusion


